// "Import power" — fetches the bundled catalog of every shipped power
// (generated by `scripts/gen-builtin-powers-catalog.ts`) and turns a chosen
// entry into an editable `PowerDraft` appended to the current origin.
//
// The mapping mirrors the datapack importer's power handling exactly (see
// `buildDraft` in `./import.ts`): the draft's `fields` is the power body with
// its `type` key removed; `type` is lifted out separately. So an imported power
// round-trips — exporting reproduces the original body (the serializer re-adds
// `type` and spreads `fields`).

import { base } from '$app/paths';

import type { PowerDraft } from '$lib/stores/originDraft';

/** One selectable built-in power (the picker's view + the body to copy). */
export interface BuiltinPowerEntry {
	/** Fully-qualified power id, e.g. `neoorigins:sword_immortal`. */
	id: string;
	/** Path segment of the id (the file name without `.json`). */
	localId: string;
	/** Human display name. */
	name: string;
	/** The power body's `type`, e.g. `neoorigins:active_ability`. */
	type: string;
	/** The full power JSON body, verbatim (includes `type`). */
	powerBody: Record<string, unknown>;
}

interface BuiltinPowerCatalog {
	generatedAt: string;
	namespace: string;
	entries: BuiltinPowerEntry[];
}

let cache: Promise<BuiltinPowerCatalog> | null = null;

/** Fetch (and memoize) the built-in power catalog from static assets. */
export function loadBuiltinPowerCatalog(): Promise<BuiltinPowerCatalog> {
	if (!cache) {
		cache = fetch(`${base}/builtin-powers-catalog.json`).then((res) => {
			if (!res.ok) throw new Error(`builtin-powers-catalog.json → HTTP ${res.status}`);
			return res.json() as Promise<BuiltinPowerCatalog>;
		});
		// Don't cache a rejected fetch — let the next call retry.
		cache.catch(() => {
			cache = null;
		});
	}
	return cache;
}

/**
 * Derive a unique local id for a newly-imported power. Starts from the source
 * `localId`; if that collides with an existing draft power id, appends `_copy`,
 * then `_2`, `_3`, … until free — matching the "append _copy/_2" dedupe rule.
 */
export function uniquePowerId(localId: string, existing: readonly PowerDraft[]): string {
	const used = new Set(existing.map((p) => p.id));
	if (!used.has(localId)) return localId;
	const copy = `${localId}_copy`;
	if (!used.has(copy)) return copy;
	let n = 2;
	while (used.has(`${copy}_${n}`)) n += 1;
	return `${copy}_${n}`;
}

/**
 * Deep-copy a catalog entry into a new `PowerDraft`. `fields` is the power body
 * minus its `type` key (mirrors `buildDraft`); `type` is lifted out; `id` is a
 * unique local id deduped against the existing draft powers.
 */
export function builtinPowerToDraft(
	entry: BuiltinPowerEntry,
	existing: readonly PowerDraft[]
): PowerDraft {
	// Deep-clone via JSON round-trip rather than structuredClone. The picker
	// holds the catalog in a Svelte `$state`, which deeply wraps each entry (and
	// its powerBody) in a reactive Proxy — and structuredClone throws
	// DataCloneError on a Proxy. Power bodies are pure JSON, so a JSON round-trip
	// clones losslessly and strips the proxy to a plain object.
	const body = JSON.parse(JSON.stringify(entry.powerBody)) as Record<string, unknown>;
	const type = typeof body.type === 'string' ? body.type : entry.type;
	const fields: Record<string, unknown> = {};
	for (const [k, v] of Object.entries(body)) {
		if (k === 'type') continue;
		fields[k] = v;
	}
	return {
		id: uniquePowerId(entry.localId, existing),
		type,
		fields
	};
}
