package com.cyberday1.neoorigins.event;

import com.cyberday1.neoorigins.api.mob_origin.DropEntry;
import com.cyberday1.neoorigins.api.mob_origin.DropRules;
import com.cyberday1.neoorigins.api.mob_origin.MobOrigin;
import com.cyberday1.neoorigins.attachment.EntityAttachments;
import com.cyberday1.neoorigins.attachment.MobOriginData;
import com.cyberday1.neoorigins.data.MobOriginDataManager;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.neoforged.neoforge.common.loot.IGlobalLootModifier;
import net.neoforged.neoforge.common.loot.LootModifier;

import java.util.Optional;

/**
 * Global loot modifier that layers a mob origin's {@code DropRules} onto the
 * mob's vanilla loot at kill time.
 *
 * <p>Fast-path: when the dropping entity has no {@link MobOriginData} attachment,
 * no origin id, no resolved {@link MobOrigin}, or empty {@link DropRules}, the
 * modifier returns {@code generatedLoot} unchanged with zero allocations. The
 * carrier file activating this modifier is shipped by either the world datapack
 * (generated by {@link com.cyberday1.neoorigins.service.MobLootModifierGenerator})
 * or any pack-author-owned datapack — either way, the static cost is one
 * attachment lookup per loot generation.
 */
public final class MobOriginDropsLootModifier extends LootModifier {

    public static final MapCodec<MobOriginDropsLootModifier> CODEC =
        RecordCodecBuilder.mapCodec(inst -> codecStart(inst)
            .apply(inst, MobOriginDropsLootModifier::new));

    // 26.1 LootModifier carries a `priority` field added in its codecStart's P2.
    public MobOriginDropsLootModifier(LootItemCondition[] conditions, int priority) {
        super(conditions, priority);
    }

    @Override
    protected ObjectArrayList<ItemStack> doApply(ObjectArrayList<ItemStack> generatedLoot,
                                                 LootContext context) {
        // 26.1: LootContext.getParamOrNull → getOptionalParameter; the param key
        // is now ContextKey<T> in net.minecraft.util.context (LootContextParams
        // still hosts the constants, just typed as ContextKey).
        Entity entity = context.getOptionalParameter(LootContextParams.THIS_ENTITY);
        if (!(entity instanceof LivingEntity living) || entity instanceof Player) return generatedLoot;

        MobOriginData data = living.getData(EntityAttachments.mobOriginData());
        Optional<Identifier> originId = data.getOriginId();
        if (originId.isEmpty()) return generatedLoot;

        MobOrigin origin = MobOriginDataManager.INSTANCE.getMobOrigin(originId.get());
        if (origin == null) return generatedLoot;

        DropRules rules = origin.dropRules();
        if (rules.isEmpty()) return generatedLoot;

        if (rules.mode() == DropRules.DropMode.REPLACE) generatedLoot.clear();

        RandomSource random = context.getRandom();
        if (rules.strategy() == DropRules.Strategy.WEIGHTED_POOL) {
            rollWeightedPool(rules, generatedLoot, random);
        } else {
            rollIndependent(rules, generatedLoot, random);
        }
        return generatedLoot;
    }

    private static void rollIndependent(DropRules rules,
                                        ObjectArrayList<ItemStack> out,
                                        RandomSource random) {
        for (DropEntry e : rules.entries()) {
            Item item = resolveItem(e.item());
            if (item == null) continue;
            int rolls = Math.max(1, e.rolls());
            for (int i = 0; i < rolls; i++) {
                if (e.chance() < 1.0 && random.nextDouble() >= e.chance()) continue;
                int count = e.count().sample(toJavaRandom(random));
                if (count > 0) out.add(new ItemStack(item, count));
            }
        }
    }

    private static void rollWeightedPool(DropRules rules,
                                         ObjectArrayList<ItemStack> out,
                                         RandomSource random) {
        int rolls = Math.max(0, rules.poolRolls());
        if (rolls == 0) return;
        int total = 0;
        for (DropEntry e : rules.entries()) total += Math.max(0, e.weight());
        if (total <= 0) return;

        for (int i = 0; i < rolls; i++) {
            int pick = random.nextInt(total);
            DropEntry chosen = null;
            for (DropEntry e : rules.entries()) {
                int w = Math.max(0, e.weight());
                if (w == 0) continue;
                if (pick < w) { chosen = e; break; }
                pick -= w;
            }
            if (chosen == null) continue;
            Item item = resolveItem(chosen.item());
            if (item == null) continue;
            int count = chosen.count().sample(toJavaRandom(random));
            if (count > 0) out.add(new ItemStack(item, count));
        }
    }

    private static Item resolveItem(Identifier id) {
        return BuiltInRegistries.ITEM.getOptional(id).orElse(null);
    }

    /** {@link com.cyberday1.neoorigins.api.mob_origin.IntRange#sample} takes a
     *  {@link java.util.Random}; bridge from the loot context's {@link RandomSource}. */
    private static java.util.Random toJavaRandom(RandomSource src) {
        return new java.util.Random() {
            @Override public int nextInt(int bound) { return src.nextInt(bound); }
            @Override public int nextInt() { return src.nextInt(); }
            @Override public double nextDouble() { return src.nextDouble(); }
            @Override public long nextLong() { return src.nextLong(); }
            @Override public boolean nextBoolean() { return src.nextBoolean(); }
            @Override public float nextFloat() { return src.nextFloat(); }
        };
    }

    @Override
    public MapCodec<? extends IGlobalLootModifier> codec() {
        return MobOriginLootModifiers.MOB_ORIGIN_DROPS.get();
    }
}
